name: my-cron
on:
  schedule:
    - cron: '25 8 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://satoyama.vercel.app/api/datafetcher' \
          --header 'Authorization: Bearer ${{ secrets.AUTHKEY }}'
