name: my-cron
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url '${{ secrets.URL }}' \
          --header 'Authorization: Bearer ${{ secrets.AUTHKEY }}'
