name: updateNewData
on:
  schedule:
    - cron: '30 21 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url '${{ secrets.UPDATEURL }}' \
          --header 'Authorization: Bearer ${{ secrets.AUTHKEY }}'
